version: '3.3'
services:
  junior-java-backend-assignment:
    build:
      context: '.'
    ports:
      - '8080:8080/tcp'
  database:
    container_name: pgdb
    image: 'postgres:9.6'
    environment:
      - 'POSTGRES_DB=palindrome'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - './database:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432/tcp'
